# Generated by Django 3.2.23 on 2023-12-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('ArtistaID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Tipo_documento', models.CharField(max_length=100)),
            ],
        ),
    ]
